### PR TITLE
fix: refine value generating logic

### LINKED ISSUE #28: Allowed attribute string value edge cases
**Description**

> Tell us more about the problem that you're running into. What did you see? What did you expect to
> see?

This likely needs broken down into more issues, but when running the config generator against this repo, here is the manual cleanup that I had to do:

https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3854/commits/ec74fd5f438c9b63b629c38ecce139477f22453d

- [ ] Double quotes

Some values had double quotes, e.g.:

```yml
        - '"lg"'
        - '"max"'
        - '"md"'
        - '"sm"'
        - '"xl"'
        - '"xs"'
```

- [ ] Prop types

I was surprised to see prop types as valid values, e.g.:

```yml
        - |-
          PropTypes.shape({
            peak: PropTypes.number,
            meterTotal: PropTypes.number,
            meterUnit: PropTypes.string,
            totalFormatter: PropTypes.func,
            legendPosition: PropTypes.string,
            ...ChartColorPropType,
          })
```

- [ ] Empty strings

There were a few empty strings that shouldn't have been there? Maybe these are okay, if it's value to set a prop with an empty string.

```yml
        - ''
```

- [ ] Object.values

I'm guessing we don't want executable JS as valid values? E.g.:

```yml
        - ...Object.values(ITEM_VALUE_KEYS)
```

**Steps to reproduce**

> How do we reproduce the error? Please be as specific as you can.

1. https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3854/commits/ec74fd5f438c9b63b629c38ecce139477f22453d

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #28 

Refines config generator logic for retrieving attribute values to:
- Remove double quotes ("") from beginning and end of strings
- Ignore empty/undefined strings
- Do not capture objects/stringified objects

#### Changelog

**New**

- use new `retrieveStringValue` function to treat attribute values before storing and discard `computed` vales

#### Testing / reviewing

- Clone this repository:
     - `npm install`
     - `npm run build`
- From local test repo (can use https://github.com/carbon-design-system/carbon-addons-iot-react):
     - `npx -y @ibm/telemetry-js-config-generator --endpoint=1234 --id=hi123 --files ./src/**/*.(tsx|js|jsx) --fi
le-path=deployed-telemetry.yml` from within instrumented (packages/react) dir 
     - `node /Users/[User]/Desktop/Projects/telemetry-js-config-generator/dist/generate-config-file.js --endpoint=1234 --id=hi123 --files ./src/**/*.(tsx|js|jsx) --file-path=pr-telemetry.yml` from within instrumented (packages/react) dir (must be the path to your local clone of telemetry config generator)
     - Compare the two generated files (might want to use `Partial Diff` vs code extension). Ensure new `pr-telemetry.yml` doesn't have any of the issues that the `deployed-telemetry.yml` presents and no regressions

### CODE REVIEW

File: src/generate-config-file.ts [hunk 1]
```diff
@@ -162,6 +162,24 @@ async function generateComponentData(files: string[], ignore: string[] = []): Pr
...
+  if (val.computed) {
+    return
+  }
+  let sanitizedVal
+  // fix for "'top'" double quotation issue
+  if (
+    (val.value.startsWith("'") && val.value.endsWith("'")) ||
+    (val.value.startsWith('"') && val.value.endsWith('"'))
+  ) {
+    sanitizedVal = val.value.substring(1, val.value.length - 1)
```
Comment (jdharvey-ibm) [inline src/generate-config-file.ts:175]: idk if this actually matters or not, but there's an edge case here where if the string is the string `"`, then this will still return '"'. Same for the single quote case. Not sure if that's the desired behavior or not.

**Review by jdharvey-ibm — APPROVED** [review]

File: src/generate-config-file.ts (hunk 1 above)
Comment (francinelucca) [reply src/generate-config-file.ts:175]: it will end up as an empty string which will then be ignored by lines 194, 204 & 215 so I think it'll be fine
image

**Review by mattrosno — COMMENTED** [review]
Running this against the latest version of https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3854, I see it removing duplicate values and always using double quotes for strings. This looks good.

```
cd packages/react
node /Users/mattrosno/Documents/GitHub/telemetry-js-config-generator/dist/generate-config-file.js --id 57ff13d6-cb2e-4a9c-8489-a1c7ceea1b16 --endpoint https://collector-prod.1am6wm210aow.us-south.codeengine.appdomain.cloud/v1/metrics --files ./src/**/*.(tsx|js|jsx)
```

image

**Review by mattrosno — APPROVED** [review]
Running this against the commit before my manual cleanup here: https://github.com/carbon-design-system/carbon-addons-iot-react/commit/ec74fd5f438c9b63b629c38ecce139477f22453d

I'm seeing all 4 tasks from https://github.com/ibm-telemetry/telemetry-js-config-generator/issues/28 fixed. LGTM!

image

image

image
